### ISSUE TITLE
Screen/Lockscreen not touchable/responding while time-vibrating

### ISSUE THREAD

**Issue by Hans-Maulwurf** [Burrit0z/BuzzTime#1]
When I press the side-button, the time is vibrating. But while vibrating, the lockscreen is not touchable/responding. Would be great to either:
* make everything touchable and responding while it is vibrating
* or make vibrating to double press the side button
* or add possibility to make an own activator gesture

anyway, great work :)

**Comment by Burrit0z** [comment]
I could definitely add another activation gesture, I just originally didn’t include that because I thought it might conflict with Apple Pay. 

It does indeed freeze the screen, which is purposeful because some undesirable bugs were occurring otherwise. (Ie notifications or calls coming in were either messing up the vibrations or sending the user to safe mode). This is probably something I should have mentioned. 

Thanks for your help!
