### ISSUE TITLE
BuzzTime not downloading and installing 

### ISSUE THREAD

**Issue by CreeperGaming089** [Burrit0z/BuzzTime#3]
Whenever I go into the Sileo store and I try to download and install BuzzTime, it tries to download it, but it never does. It says the amount of kb it needs and it does, but it never installs. I don’t know what the issue is if it’s on my end or not. My phone is on 12.4 and it’s a iPhone 8.
![5C252685-4DA0-4B21-9916-51DDA49A9F97](https://user-images.githubusercontent.com/30304544/74534416-a7fa9400-4f01-11ea-82cb-1a499a16ec1c.png)

**Comment by Burrit0z** [comment]
I really wish I could get my repo to work on Sileo, and I tried to combat that by adding it to bigBoss, until I realized bigBoss doesn’t work on Sileo either. If you have zebra/installer, use that. Otherwise, you can directly download the .deb file from here:

https://raw.githubusercontent.com/Burrit0z/repo/master/debs/com.burritoz.buzztime_1.0_iphoneos-arm.deb

**Comment by CreeperGaming089** [comment]
Hey, thank you for the .deb file! I used Filza to instal it and it worked! This app is pretty cool to use and it’s useful.

**Comment by Burrit0z** [comment]
No problem, glad I could help, I really need to figure out why the repo doesn’t work, but then again Sileo has a completely different repo system. (Many repos don’t work in Sileo, it seems)
